project:
  type: website
  output-dir: docs
website:
  title: "Deep Learning y Privacidad"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lzeladam
      - icon: twitter
        href: https://twitter.com/lzeladam
      - icon: linkedin
        href: https://www.linkedin.com/in/lzeladam/
  page-footer: "Hecho por Alexander Zelada y Quarto"
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css



