project:
  type: website
  output-dir: docs
website:
  title: "Alexander Zelada"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lzeladam
      - icon: twitter
        href: https://twitter.com/lzeladam
format:
  html:
    theme: cosmo
    css: styles.css



